### ISSUE TITLE
Add copyright logo at footer

### ISSUE THREAD

**Issue by mohitbalwani** [mohitbalwani/Citi-site#2]

**Comment by mohitbalwani** [comment]
@BrotatoBoi The logo is breaking the site because of it's very big size. Try resizing it to fit at bottom before "2021-22".

**Comment by BrotatoBoi** [comment]
@mohitbalwani It seems fine on my end. I am using both FireFox and Chromium on Kali Linux. I can resize the screen to the littlest size possible and it still looks good. May you please tell me how you are viewing my changes (i.e. Browser and Device) to see the breaks.


However if you would like the CopyRight Icon to the left of "2021-22" I will send the PR with that. 

And thank you for taking the time to review my changes. :)

The following is my screen, note the sideways navigation and submit button in the Phone text field is in the source and not from the CopyRight Icon.

![FireFox-CR-Icon-OK](https://user-images.githubusercontent.com/33473023/139533749-04e1b1ab-a644-409a-9926-795a6fca3339.png)
![Chrome-CR-Icon-OK](https://user-images.githubusercontent.com/33473023/139533754-964dcefe-675f-4532-b27f-99ce6f1710d4.png)
